# Form implementation generated from reading ui file 'qtdesign2.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_EduLab(object):
    def setupUi(self, EduLab):
        EduLab.setObjectName("EduLab")
        EduLab.setWindowModality(QtCore.Qt.WindowModality.NonModal)
        EduLab.resize(800, 600)
        EduLab.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logo/icon_blck.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        EduLab.setWindowIcon(icon)
        EduLab.setStatusTip("")
        EduLab.setStyleSheet("\n"
"background-color: rgb(15, 15, 15);")
        self.centralwidget = QtWidgets.QWidget(parent=EduLab)
        self.centralwidget.setObjectName("centralwidget")
        self.inputYandex = QtWidgets.QTextEdit(self.centralwidget)
        self.inputYandex.setGeometry(QtCore.QRect(290, 50, 481, 121))
        self.inputYandex.setStyleSheet("QTextEdit {\n"
                                       "background-color: #1D1D1D;\n"
                                       "color: white;\n"
                                       "border: 2px solid transparent;\n"
                                       "border-radius: 6px;\n"
                                       "}")
        self.inputYandex.setObjectName("inputYandex")

        self.outputYandex = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.outputYandex.setGeometry(QtCore.QRect(290, 230, 481, 131))
        self.outputYandex.setStyleSheet("QTextEdit {\n"
"background-color: #1D1D1D;\n"
"color: white;\n"
"border: 2px solid transparent;\n"
"  border-radius: 6px;\n"
"}")
        self.outputYandex.setObjectName("outputYandex")
        self.paste1 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.paste1.setGeometry(QtCore.QRect(320, 180, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.paste1.setFont(font)
        self.paste1.setStyleSheet("QPushButton {\n"
"background-color: #1D1D1D;\n"
"color: white;\n"
"border: 2px solid transparent;\n"
"  border-radius: 6px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #252525;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: gray;\n"
"}")
        self.paste1.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/paste.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.paste1.setIcon(icon1)
        self.paste1.setIconSize(QtCore.QSize(18, 18))
        self.paste1.setObjectName("paste1")
        self.errorlog = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.errorlog.setGeometry(QtCore.QRect(290, 420, 481, 81))
        self.errorlog.setStyleSheet("QTextEdit {\n"
"background-color: #1B1B1B;\n"
"color: white;\n"
"border: 2px solid transparent;\n"
"  border-radius: 6px;\n"
"}")
        self.errorlog.setObjectName("errorlog")
        self.checktext = QtWidgets.QPushButton(parent=self.centralwidget)
        self.checktext.setGeometry(QtCore.QRect(450, 180, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checktext.setFont(font)
        self.checktext.setStyleSheet("QPushButton {\n"
"background-color: #1E1E1E;\n"
"color: white;\n"
"border: 2px solid transparent;\n"
"  border-radius: 6px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #252525;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: green;\n"
"}")
        self.checktext.setObjectName("checktext")
        self.copy1 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.copy1.setGeometry(QtCore.QRect(290, 180, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.copy1.setFont(font)
        self.copy1.setStyleSheet("QPushButton {\n"
"background-color: #1D1D1D;\n"
"color: white;\n"
"border: 2px solid transparent;\n"
"  border-radius: 6px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #252525;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: gray;\n"
"}\n"
"\n"
"\n"
"")
        self.copy1.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/copy.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.copy1.setIcon(icon2)
        self.copy1.setIconSize(QtCore.QSize(18, 18))
        self.copy1.setObjectName("copy1")
        self.delete1 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.delete1.setGeometry(QtCore.QRect(350, 180, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.delete1.setFont(font)
        self.delete1.setStyleSheet("QPushButton {\n"
"background-color: #1D1D1D;\n"
"color: white;\n"
"border: 2px solid transparent;\n"
"  border-radius: 6px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #252525;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: #EE3232;\n"
"}")
        self.delete1.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/delete text.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.delete1.setIcon(icon3)
        self.delete1.setIconSize(QtCore.QSize(18, 18))
        self.delete1.setObjectName("delete1")
        self.copy2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.copy2.setGeometry(QtCore.QRect(290, 370, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.copy2.setFont(font)
        self.copy2.setStyleSheet("QPushButton {\n"
"background-color: #1D1D1D;\n"
"color: white;\n"
"border: 2px solid transparent;\n"
"  border-radius: 6px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #252525;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: gray;\n"
"}\n"
"\n"
"\n"
"")
        self.copy2.setText("")
        self.copy2.setIcon(icon2)
        self.copy2.setIconSize(QtCore.QSize(18, 18))
        self.copy2.setObjectName("copy2")
        self.delete2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.delete2.setGeometry(QtCore.QRect(320, 370, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.delete2.setFont(font)
        self.delete2.setStyleSheet("QPushButton {\n"
"background-color: #1D1D1D;\n"
"color: white;\n"
"border: 2px solid transparent;\n"
"  border-radius: 6px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #252525;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: #EE3232;\n"
"}")
        self.delete2.setText("")
        self.delete2.setIcon(icon3)
        self.delete2.setIconSize(QtCore.QSize(18, 18))
        self.delete2.setObjectName("delete2")
        self.opentext1 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.opentext1.setGeometry(QtCore.QRect(380, 180, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.opentext1.setFont(font)
        self.opentext1.setStyleSheet("QPushButton {\n"
"background-color: #1E1E1E;\n"
"color: white;\n"
"border: 2px solid transparent;\n"
"  border-radius: 6px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #252525;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: gray;\n"
"}")
        self.opentext1.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/text open.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.opentext1.setIcon(icon4)
        self.opentext1.setObjectName("opentext1")
        self.opentext2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.opentext2.setGeometry(QtCore.QRect(350, 370, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.opentext2.setFont(font)
        self.opentext2.setStyleSheet("QPushButton {\n"
"background-color: #1E1E1E;\n"
"color: white;\n"
"border: 2px solid transparent;\n"
"  border-radius: 6px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #252525;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: gray;\n"
"}")
        self.opentext2.setText("")
        self.opentext2.setIcon(icon4)
        self.opentext2.setObjectName("opentext2")
        self.errorcopy = QtWidgets.QPushButton(parent=self.centralwidget)
        self.errorcopy.setGeometry(QtCore.QRect(290, 510, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.errorcopy.setFont(font)
        self.errorcopy.setStyleSheet("QPushButton {\n"
"background-color: #1E1E1E;\n"
"color: white;\n"
"border: 2px solid transparent;\n"
"  border-radius: 6px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #252525;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: gray;\n"
"}")
        self.errorcopy.setText("")
        self.errorcopy.setIcon(icon2)
        self.errorcopy.setObjectName("errorcopy")
        self.deleteerrors = QtWidgets.QPushButton(parent=self.centralwidget)
        self.deleteerrors.setGeometry(QtCore.QRect(370, 510, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.deleteerrors.setFont(font)
        self.deleteerrors.setStyleSheet("QPushButton {\n"
"background-color: #1E1E1E;\n"
"color: white;\n"
"border: 2px solid transparent;\n"
"  border-radius: 6px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #252525;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: red;\n"
"}")
        self.deleteerrors.setText("")
        self.deleteerrors.setIcon(icon3)
        self.deleteerrors.setObjectName("deleteerrors")
        self.open1 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.open1.setGeometry(QtCore.QRect(20, 240, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.open1.setFont(font)
        self.open1.setStyleSheet("QPushButton {\n"
"background-color: #1E1E1E;\n"
"color: white;\n"
"border: 2px solid transparent;\n"
"  border-radius: 6px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #252525;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: green;\n"
"}")
        self.open1.setObjectName("open1")
        self.open2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.open2.setGeometry(QtCore.QRect(20, 280, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.open2.setFont(font)
        self.open2.setStyleSheet("QPushButton {\n"
"background-color: #1E1E1E;\n"
"color: white;\n"
"border: 2px solid transparent;\n"
"  border-radius: 6px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #252525;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: green;\n"
"}")
        self.open2.setObjectName("open2")
        self.open3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.open3.setGeometry(QtCore.QRect(20, 320, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.open3.setFont(font)
        self.open3.setStyleSheet("QPushButton {\n"
"background-color: #1E1E1E;\n"
"color: white;\n"
"border: 2px solid transparent;\n"
"  border-radius: 6px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #252525;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: green;\n"
"}")
        self.open3.setObjectName("open3")
        self.open4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.open4.setGeometry(QtCore.QRect(20, 360, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.open4.setFont(font)
        self.open4.setStyleSheet("QPushButton {\n"
"background-color: #1E1E1E;\n"
"color: white;\n"
"border: 2px solid transparent;\n"
"  border-radius: 6px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #252525;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: green;\n"
"}")
        self.open4.setObjectName("open4")
        self.open5 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.open5.setGeometry(QtCore.QRect(20, 400, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.open5.setFont(font)
        self.open5.setStyleSheet("QPushButton {\n"
"background-color: #1E1E1E;\n"
"color: white;\n"
"border: 2px solid transparent;\n"
"  border-radius: 6px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #252525;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: green;\n"
"}")
        self.open5.setObjectName("open5")
        self.home = QtWidgets.QPushButton(parent=self.centralwidget)
        self.home.setGeometry(QtCore.QRect(20, 200, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.home.setFont(font)
        self.home.setStyleSheet("QPushButton {\n"
"background-color: #1D1D1D;\n"
"color: white;\n"
"border: 2px solid transparent;\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #252525;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: green;\n"
"}\n"
"\n"
"\n"
"")
        self.home.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/home.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.home.setIcon(icon5)
        self.home.setIconSize(QtCore.QSize(18, 18))
        self.home.setObjectName("home")
        self.settings = QtWidgets.QPushButton(parent=self.centralwidget)
        self.settings.setGeometry(QtCore.QRect(60, 200, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.settings.setFont(font)
        self.settings.setStyleSheet("QPushButton {\n"
"background-color: #1D1D1D;\n"
"color: white;\n"
"border: 2px solid transparent;\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #252525;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: red;\n"
"}\n"
"\n"
"\n"
"")
        self.settings.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/settings.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.settings.setIcon(icon6)
        self.settings.setIconSize(QtCore.QSize(18, 18))
        self.settings.setObjectName("settings")
        self.openfile1 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.openfile1.setGeometry(QtCore.QRect(410, 180, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.openfile1.setFont(font)
        self.openfile1.setStyleSheet("QPushButton {\n"
"background-color: #1D1D1D;\n"
"color: white;\n"
"border: 2px solid transparent;\n"
"  border-radius: 6px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #252525;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: gray;\n"
"}\n"
"\n"
"\n"
"")
        self.openfile1.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icons/filepick.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.openfile1.setIcon(icon7)
        self.openfile1.setIconSize(QtCore.QSize(18, 18))
        self.openfile1.setObjectName("openfile1")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(-10, -10, 821, 51))
        self.widget.setStyleSheet("QWidget {\n"
"background-color: rgb(38, 38, 38);\n"
"color: white;\n"
"border: \n"
"6px solid transparent;\n"
"  border-radius: 6px;\n"
"}\n"
"")
        self.widget.setObjectName("widget")
        self.logo = QtWidgets.QPushButton(parent=self.widget)
        self.logo.setGeometry(QtCore.QRect(20, 10, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.logo.setFont(font)
        self.logo.setStyleSheet("QPushButton {\n"
"background-color: transparent;\n"
"color: white;\n"
"border: 5px solid transparent;\n"
"  border-radius: 6px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #252525;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: gray;\n"
"}\n"
"\n"
"\n"
"")
        self.logo.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("icons/logo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.logo.setIcon(icon8)
        self.logo.setIconSize(QtCore.QSize(30, 30))
        self.logo.setObjectName("logo")
        self.close = QtWidgets.QPushButton(parent=self.widget)
        self.close.setGeometry(QtCore.QRect(760, 20, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.close.setFont(font)
        self.close.setStyleSheet("QPushButton {\n"
"background-color: #1D1D1D;\n"
"color: white;\n"
"border: 2px solid transparent;\n"
"  border-radius: 6px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #252525;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: #EE3232;\n"
"}")
        self.close.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("../../../Downloads/close.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.close.setIcon(icon9)
        self.close.setIconSize(QtCore.QSize(18, 18))
        self.close.setObjectName("close")
        self.rollup = QtWidgets.QPushButton(parent=self.widget)
        self.rollup.setGeometry(QtCore.QRect(740, 20, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.rollup.setFont(font)
        self.rollup.setStyleSheet("QPushButton {\n"
"background-color: #1D1D1D;\n"
"color: white;\n"
"border: 2px solid transparent;\n"
"  border-radius: 6px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #252525;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: gray;\n"
"}")
        self.rollup.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("../../../Downloads/remove.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.rollup.setIcon(icon10)
        self.rollup.setIconSize(QtCore.QSize(18, 18))
        self.rollup.setObjectName("rollup")
        self.openerrors = QtWidgets.QPushButton(parent=self.centralwidget)
        self.openerrors.setGeometry(QtCore.QRect(330, 510, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.openerrors.setFont(font)
        self.openerrors.setStyleSheet("QPushButton {\n"
"background-color: #1E1E1E;\n"
"color: white;\n"
"border: 2px solid transparent;\n"
"  border-radius: 6px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #252525;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: gray;\n"
"}")
        self.openerrors.setText("")
        self.openerrors.setIcon(icon4)
        self.openerrors.setObjectName("openerrors")
        EduLab.setCentralWidget(self.centralwidget)

        self.retranslateUi(EduLab)
        QtCore.QMetaObject.connectSlotsByName(EduLab)

    def retranslateUi(self, EduLab):
        _translate = QtCore.QCoreApplication.translate
        EduLab.setWindowTitle(_translate("EduLab", "EduLab"))
        self.checktext.setText(_translate("EduLab", "Исправить текст"))
        self.open1.setText(_translate("EduLab", "Исправитель текста"))
        self.open2.setText(_translate("EduLab", "example"))
        self.open3.setText(_translate("EduLab", "example"))
        self.open4.setText(_translate("EduLab", "example"))
        self.open5.setText(_translate("EduLab", "example"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EduLab = QtWidgets.QMainWindow()
    ui = Ui_EduLab()
    ui.setupUi(EduLab)
    EduLab.show()
    sys.exit(app.exec())
