# Form implementation generated from reading ui file 'qtdesign2.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_EduLab(object):
    def setupUi(self, EduLab):
        EduLab.setObjectName("EduLab")
        EduLab.setWindowModality(QtCore.Qt.WindowModality.NonModal)
        EduLab.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        EduLab.setFont(font)
        EduLab.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logo/icon_blck.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        EduLab.setWindowIcon(icon)
        EduLab.setStatusTip("")
        EduLab.setStyleSheet("\n"
"background-color: rgb(15, 15, 15);")
        self.centralwidget = QtWidgets.QWidget(parent=EduLab)
        self.centralwidget.setObjectName("centralwidget")
        self.open1_textreworker_pg3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.open1_textreworker_pg3.setGeometry(QtCore.QRect(20, 240, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        self.open1_textreworker_pg3.setFont(font)
        self.open1_textreworker_pg3.setStyleSheet("QPushButton {\n"
"background-color: #1E1E1E;\n"
"color: white;\n"
"border: 2px solid transparent;\n"
"  border-radius: 6px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #252525;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: gray;\n"
"}")
        self.open1_textreworker_pg3.setObjectName("open1_textreworker_pg3")
        self.home_pg1 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.home_pg1.setGeometry(QtCore.QRect(20, 200, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.home_pg1.setFont(font)
        self.home_pg1.setStyleSheet("QPushButton {\n"
"background-color: #1D1D1D;\n"
"color: white;\n"
"border: 2px solid transparent;\n"
"  border-radius: 6px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #252525;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: green;\n"
"}\n"
"\n"
"\n"
"")
        self.home_pg1.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/home.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.home_pg1.setIcon(icon1)
        self.home_pg1.setIconSize(QtCore.QSize(18, 18))
        self.home_pg1.setObjectName("home_pg1")
        self.settings_pg2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.settings_pg2.setGeometry(QtCore.QRect(60, 200, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.settings_pg2.setFont(font)
        self.settings_pg2.setStyleSheet("QPushButton {\n"
"background-color: #1D1D1D;\n"
"color: white;\n"
"border: 2px solid transparent;\n"
"  border-radius: 6px;\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #252525;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: red;\n"
"}\n"
"\n"
"\n"
"")
        self.settings_pg2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/settings.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.settings_pg2.setIcon(icon2)
        self.settings_pg2.setIconSize(QtCore.QSize(18, 18))
        self.settings_pg2.setObjectName("settings_pg2")
        self.logo = QtWidgets.QPushButton(parent=self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(20, 50, 141, 131))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.logo.setFont(font)
        self.logo.setStyleSheet("QPushButton {\n"
"background-color: transparent;\n"
"color: white;\n"
"border: 5px solid transparent;\n"
"  border-radius: 6px;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: gray;\n"
"}\n"
"\n"
"\n"
"")
        self.logo.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/logo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.logo.setIcon(icon3)
        self.logo.setIconSize(QtCore.QSize(130, 130))
        self.logo.setObjectName("logo")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(250, 40, 521, 531))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(9)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.ai_input = QtWidgets.QTextEdit(parent=self.page)
        self.ai_input.setGeometry(QtCore.QRect(20, 410, 501, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        self.ai_input.setFont(font)
        self.ai_input.setStyleSheet("QTextEdit {\n"
"background-color: #1E1E1E;\n"
"color: white;\n"
"border: 14px solid transparent;\n"
"  border-radius: 25px;\n"
"}\n"
"QTextEdit:hover {\n"
"background-color: #1D1D1D;\n"
"}")
        self.ai_input.setObjectName("ai_input")
        self.ai_send_button = QtWidgets.QPushButton(parent=self.page)
        self.ai_send_button.setGeometry(QtCore.QRect(480, 420, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.ai_send_button.setFont(font)
        self.ai_send_button.setStyleSheet("QPushButton {\n"
"background-color: #0E0E0E;\n"
"color: white;\n"
"border: 1px solid transparent;\n"
"  border-radius: 15px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #252525;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: #878383;\n"
"}")
        self.ai_send_button.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/send.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.ai_send_button.setIcon(icon4)
        self.ai_send_button.setObjectName("ai_send_button")
        self.ai_output = QtWidgets.QTextEdit(parent=self.page)
        self.ai_output.setGeometry(QtCore.QRect(30, 20, 481, 391))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        self.ai_output.setFont(font)
        self.ai_output.setStyleSheet("QTextEdit {\n"
"background-color: #1E1E1E;\n"
"color: white;\n"
"border: 2px solid transparent;\n"
"  border-radius: 6px;\n"
"}")
        self.ai_output.setObjectName("ai_output")
        self.ai_chat_text = QtWidgets.QLabel(parent=self.page)
        self.ai_chat_text.setGeometry(QtCore.QRect(30, 0, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        self.ai_chat_text.setFont(font)
        self.ai_chat_text.setStyleSheet("QLabel {\n"
"background-color: ;\n"
"color: white;\n"
"border: 2px solid transparent;\n"
"  border-radius: 6px;\n"
"}")
        self.ai_chat_text.setObjectName("ai_chat_text")
        self.stackedWidget.addWidget(self.page)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label = QtWidgets.QLabel(parent=self.page_3)
        self.label.setGeometry(QtCore.QRect(30, 20, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"background-color: ;\n"
"color: white;\n"
"border: 2px solid transparent;\n"
"  border-radius: 6px;\n"
"}")
        self.label.setObjectName("label")
        self.llama_input_api = QtWidgets.QLineEdit(parent=self.page_3)
        self.llama_input_api.setGeometry(QtCore.QRect(30, 40, 211, 31))
        self.llama_input_api.setStyleSheet("QLineEdit {\n"
"background-color: #1E1E1E;\n"
"color: white;\n"
"border: 2px solid transparent;\n"
"  border-radius: 10px;\n"
"}\n"
"QLineEdit:hover {\n"
"background-color: #1D1D1D;\n"
"}")
        self.llama_input_api.setObjectName("llama_input_api")
        self.llama_api_add = QtWidgets.QPushButton(parent=self.page_3)
        self.llama_api_add.setGeometry(QtCore.QRect(250, 40, 31, 31))
        self.llama_api_add.setStyleSheet("QPushButton {\n"
"background-color: #1D1C1C;\n"
"color: white;\n"
"border: 2px solid transparent;\n"
"  border-radius: 15px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #252525;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: #878383;\n"
"}")
        self.llama_api_add.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/add.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.llama_api_add.setIcon(icon5)
        self.llama_api_add.setIconSize(QtCore.QSize(20, 20))
        self.llama_api_add.setObjectName("llama_api_add")
        self.chatgpt_input_api = QtWidgets.QLineEdit(parent=self.page_3)
        self.chatgpt_input_api.setGeometry(QtCore.QRect(30, 120, 211, 31))
        self.chatgpt_input_api.setStyleSheet("QLineEdit {\n"
"background-color: #1E1E1E;\n"
"color: white;\n"
"border: 2px solid transparent;\n"
"  border-radius: 10px;\n"
"}\n"
"QLineEdit:hover {\n"
"background-color: #1D1D1D;\n"
"}")
        self.chatgpt_input_api.setObjectName("chatgpt_input_api")
        self.label_2 = QtWidgets.QLabel(parent=self.page_3)
        self.label_2.setGeometry(QtCore.QRect(30, 100, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel {\n"
"background-color: ;\n"
"color: white;\n"
"border: 2px solid transparent;\n"
"  border-radius: 6px;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.chatgpt_api_add = QtWidgets.QPushButton(parent=self.page_3)
        self.chatgpt_api_add.setGeometry(QtCore.QRect(250, 120, 31, 31))
        self.chatgpt_api_add.setStyleSheet("QPushButton {\n"
"background-color: #1D1C1C;\n"
"color: white;\n"
"border: 2px solid transparent;\n"
"  border-radius: 15px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #252525;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: #878383;\n"
"}")
        self.chatgpt_api_add.setText("")
        self.chatgpt_api_add.setIcon(icon5)
        self.chatgpt_api_add.setIconSize(QtCore.QSize(20, 20))
        self.chatgpt_api_add.setObjectName("chatgpt_api_add")
        self.more_settings = QtWidgets.QLabel(parent=self.page_3)
        self.more_settings.setGeometry(QtCore.QRect(40, 170, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        self.more_settings.setFont(font)
        self.more_settings.setStyleSheet("QLabel {\n"
"background-color: ;\n"
"color: white;\n"
"border: 2px solid transparent;\n"
"  border-radius: 6px;\n"
"}")
        self.more_settings.setObjectName("more_settings")
        self.background_change_text = QtWidgets.QLabel(parent=self.page_3)
        self.background_change_text.setGeometry(QtCore.QRect(40, 220, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        self.background_change_text.setFont(font)
        self.background_change_text.setStyleSheet("QLabel {\n"
"background-color: ;\n"
"color: white;\n"
"border: 2px solid transparent;\n"
"  border-radius: 6px;\n"
"}")
        self.background_change_text.setObjectName("background_change_text")
        self.theme_text = QtWidgets.QLabel(parent=self.page_3)
        self.theme_text.setGeometry(QtCore.QRect(340, 20, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        self.theme_text.setFont(font)
        self.theme_text.setStyleSheet("QLabel {\n"
"background-color: ;\n"
"color: white;\n"
"border: 2px solid transparent;\n"
"  border-radius: 6px;\n"
"}")
        self.theme_text.setObjectName("theme_text")
        self.background_set_file_open = QtWidgets.QPushButton(parent=self.page_3)
        self.background_set_file_open.setGeometry(QtCore.QRect(40, 240, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        self.background_set_file_open.setFont(font)
        self.background_set_file_open.setStyleSheet("QPushButton {\n"
"background-color: #1E1E1E;\n"
"color: white;\n"
"border: 2px solid transparent;\n"
"  border-radius: 6px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #252525;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: gray;\n"
"}")
        self.background_set_file_open.setObjectName("background_set_file_open")
        self.background_reset = QtWidgets.QPushButton(parent=self.page_3)
        self.background_reset.setGeometry(QtCore.QRect(200, 240, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.background_reset.setFont(font)
        self.background_reset.setStyleSheet("QPushButton {\n"
"background-color: #1D1D1D;\n"
"color: white;\n"
"border: 2px solid transparent;\n"
"  border-radius: 6px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #252525;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: #EE3232;\n"
"}")
        self.background_reset.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/delete text.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.background_reset.setIcon(icon6)
        self.background_reset.setIconSize(QtCore.QSize(18, 18))
        self.background_reset.setObjectName("background_reset")
        self.set_black_theme = QtWidgets.QPushButton(parent=self.page_3)
        self.set_black_theme.setGeometry(QtCore.QRect(320, 60, 181, 81))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(11)
        font.setBold(True)
        self.set_black_theme.setFont(font)
        self.set_black_theme.setStyleSheet("QPushButton {\n"
"background-color: #1E1E1E;\n"
"color: white;\n"
"border: 2px solid transparent;\n"
"  border-radius: 6px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #252525;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: gray;\n"
"}")
        self.set_black_theme.setObjectName("set_black_theme")
        self.set_white_theme = QtWidgets.QPushButton(parent=self.page_3)
        self.set_white_theme.setGeometry(QtCore.QRect(320, 160, 181, 81))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(11)
        font.setBold(True)
        self.set_white_theme.setFont(font)
        self.set_white_theme.setStyleSheet("QPushButton {\n"
"background-color: white;\n"
"color: black;\n"
"border: 2px solid transparent;\n"
"  border-radius: 6px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: gray;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: #1E1E1E;\n"
"}")
        self.set_white_theme.setObjectName("set_white_theme")
        self.stackedWidget.addWidget(self.page_3)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.openfile1 = QtWidgets.QPushButton(parent=self.page_2)
        self.openfile1.setGeometry(QtCore.QRect(110, 140, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.openfile1.setFont(font)
        self.openfile1.setStyleSheet("QPushButton {\n"
"background-color: #1D1D1D;\n"
"color: white;\n"
"border: 2px solid transparent;\n"
"  border-radius: 6px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #252525;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: gray;\n"
"}\n"
"\n"
"\n"
"")
        self.openfile1.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icons/filepick.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.openfile1.setIcon(icon7)
        self.openfile1.setIconSize(QtCore.QSize(18, 18))
        self.openfile1.setObjectName("openfile1")
        self.outputYandex = QtWidgets.QTextEdit(parent=self.page_2)
        self.outputYandex.setGeometry(QtCore.QRect(20, 190, 491, 131))
        self.outputYandex.setStyleSheet("QTextEdit {\n"
"background-color: #1D1D1D;\n"
"color: white;\n"
"border: 2px solid transparent;\n"
"  border-radius: 6px;\n"
"}")
        self.outputYandex.setObjectName("outputYandex")
        self.paste1 = QtWidgets.QPushButton(parent=self.page_2)
        self.paste1.setGeometry(QtCore.QRect(50, 140, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.paste1.setFont(font)
        self.paste1.setStyleSheet("QPushButton {\n"
"background-color: #1D1D1D;\n"
"color: white;\n"
"border: 2px solid transparent;\n"
"  border-radius: 6px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #252525;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: gray;\n"
"}")
        self.paste1.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("icons/paste.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.paste1.setIcon(icon8)
        self.paste1.setIconSize(QtCore.QSize(18, 18))
        self.paste1.setObjectName("paste1")
        self.errorcopy = QtWidgets.QPushButton(parent=self.page_2)
        self.errorcopy.setGeometry(QtCore.QRect(20, 470, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee")
        font.setPointSize(10)
        font.setBold(True)
        self.errorcopy.setFont(font)
        self.errorcopy.setStyleSheet("QPushButton {\n"
"background-color: #1E1E1E;\n"
"color: white;\n"
"border: 2px solid transparent;\n"
"  border-radius: 6px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #252525;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: gray;\n"
"}")
        self.errorcopy.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("icons/copy.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.errorcopy.setIcon(icon9)
        self.errorcopy.setObjectName("errorcopy")
        self.delete2 = QtWidgets.QPushButton(parent=self.page_2)
        self.delete2.setGeometry(QtCore.QRect(50, 330, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.delete2.setFont(font)
        self.delete2.setStyleSheet("QPushButton {\n"
"background-color: #1D1D1D;\n"
"color: white;\n"
"border: 2px solid transparent;\n"
"  border-radius: 6px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #252525;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: #EE3232;\n"
"}")
        self.delete2.setText("")
        self.delete2.setIcon(icon6)
        self.delete2.setIconSize(QtCore.QSize(18, 18))
        self.delete2.setObjectName("delete2")
        self.inputYandex = QtWidgets.QTextEdit(parent=self.page_2)
        self.inputYandex.setGeometry(QtCore.QRect(20, 10, 491, 121))
        self.inputYandex.setStyleSheet("QTextEdit {\n"
"background-color: #1D1D1D;\n"
"color: white;\n"
"border: 2px solid transparent;\n"
"  border-radius: 6px;\n"
"}\n"
"QTextEdit:hover {\n"
"background-color: #1E1E1E;\n"
"}")
        self.inputYandex.setObjectName("inputYandex")
        self.deleteerrors = QtWidgets.QPushButton(parent=self.page_2)
        self.deleteerrors.setGeometry(QtCore.QRect(60, 470, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee")
        font.setPointSize(10)
        font.setBold(True)
        self.deleteerrors.setFont(font)
        self.deleteerrors.setStyleSheet("QPushButton {\n"
"background-color: #1E1E1E;\n"
"color: white;\n"
"border: 2px solid transparent;\n"
"  border-radius: 6px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #252525;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: red;\n"
"}")
        self.deleteerrors.setText("")
        self.deleteerrors.setIcon(icon6)
        self.deleteerrors.setObjectName("deleteerrors")
        self.copy2 = QtWidgets.QPushButton(parent=self.page_2)
        self.copy2.setGeometry(QtCore.QRect(20, 330, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.copy2.setFont(font)
        self.copy2.setStyleSheet("QPushButton {\n"
"background-color: #1D1D1D;\n"
"color: white;\n"
"border: 2px solid transparent;\n"
"  border-radius: 6px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #252525;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: gray;\n"
"}\n"
"\n"
"\n"
"")
        self.copy2.setText("")
        self.copy2.setIcon(icon9)
        self.copy2.setIconSize(QtCore.QSize(18, 18))
        self.copy2.setObjectName("copy2")
        self.copy1 = QtWidgets.QPushButton(parent=self.page_2)
        self.copy1.setGeometry(QtCore.QRect(20, 140, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.copy1.setFont(font)
        self.copy1.setStyleSheet("QPushButton {\n"
"background-color: #1D1D1D;\n"
"color: white;\n"
"border: 2px solid transparent;\n"
"  border-radius: 6px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #252525;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: gray;\n"
"}\n"
"\n"
"\n"
"")
        self.copy1.setText("")
        self.copy1.setIcon(icon9)
        self.copy1.setIconSize(QtCore.QSize(18, 18))
        self.copy1.setObjectName("copy1")
        self.delete1 = QtWidgets.QPushButton(parent=self.page_2)
        self.delete1.setGeometry(QtCore.QRect(80, 140, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.delete1.setFont(font)
        self.delete1.setStyleSheet("QPushButton {\n"
"background-color: #1D1D1D;\n"
"color: white;\n"
"border: 2px solid transparent;\n"
"  border-radius: 6px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #252525;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: #EE3232;\n"
"}")
        self.delete1.setText("")
        self.delete1.setIcon(icon6)
        self.delete1.setIconSize(QtCore.QSize(18, 18))
        self.delete1.setObjectName("delete1")
        self.checktext = QtWidgets.QPushButton(parent=self.page_2)
        self.checktext.setGeometry(QtCore.QRect(150, 140, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        self.checktext.setFont(font)
        self.checktext.setStyleSheet("QPushButton {\n"
"background-color: #1E1E1E;\n"
"color: white;\n"
"border: 2px solid transparent;\n"
"  border-radius: 6px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #252525;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: green;\n"
"}")
        self.checktext.setObjectName("checktext")
        self.errorlog = QtWidgets.QTextEdit(parent=self.page_2)
        self.errorlog.setGeometry(QtCore.QRect(20, 380, 491, 81))
        self.errorlog.setStyleSheet("QTextEdit {\n"
"background-color: #1B1B1B;\n"
"color: white;\n"
"border: 2px solid transparent;\n"
"  border-radius: 6px;\n"
"}")
        self.errorlog.setObjectName("errorlog")
        self.stackedWidget.addWidget(self.page_2)
        self.open2_translator = QtWidgets.QPushButton(parent=self.centralwidget)
        self.open2_translator.setGeometry(QtCore.QRect(20, 280, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        self.open2_translator.setFont(font)
        self.open2_translator.setStyleSheet("QPushButton {\n"
"background-color: #1E1E1E;\n"
"color: white;\n"
"border: 2px solid transparent;\n"
"  border-radius: 6px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #252525;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: gray;\n"
"}")
        self.open2_translator.setObjectName("open2_translator")
        self.open3_pptxgen = QtWidgets.QPushButton(parent=self.centralwidget)
        self.open3_pptxgen.setGeometry(QtCore.QRect(20, 320, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        self.open3_pptxgen.setFont(font)
        self.open3_pptxgen.setStyleSheet("QPushButton {\n"
"background-color: #1E1E1E;\n"
"color: white;\n"
"border: 2px solid transparent;\n"
"  border-radius: 6px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #252525;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: gray;\n"
"}")
        self.open3_pptxgen.setObjectName("open3_pptxgen")
        self.open4_imggen = QtWidgets.QPushButton(parent=self.centralwidget)
        self.open4_imggen.setGeometry(QtCore.QRect(20, 360, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        self.open4_imggen.setFont(font)
        self.open4_imggen.setStyleSheet("QPushButton {\n"
"background-color: #1E1E1E;\n"
"color: white;\n"
"border: 2px solid transparent;\n"
"  border-radius: 6px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #252525;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: gray;\n"
"}")
        self.open4_imggen.setObjectName("open4_imggen")
        self.header = QtWidgets.QWidget(parent=self.centralwidget)
        self.header.setGeometry(QtCore.QRect(0, 0, 791, 41))
        self.header.setObjectName("header")
        self.rollup = QtWidgets.QPushButton(parent=self.header)
        self.rollup.setGeometry(QtCore.QRect(740, 10, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.rollup.setFont(font)
        self.rollup.setStyleSheet("QPushButton {\n"
"background-color: #1D1D1D;\n"
"color: white;\n"
"border: 2px solid transparent;\n"
"  border-radius: 6px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #252525;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: gray;\n"
"}")
        self.rollup.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("../../../Downloads/remove.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.rollup.setIcon(icon10)
        self.rollup.setIconSize(QtCore.QSize(18, 18))
        self.rollup.setObjectName("rollup")
        self.close = QtWidgets.QPushButton(parent=self.header)
        self.close.setGeometry(QtCore.QRect(760, 10, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.close.setFont(font)
        self.close.setStyleSheet("QPushButton {\n"
"background-color: #1D1D1D;\n"
"color: white;\n"
"border: 2px solid transparent;\n"
"  border-radius: 6px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #252525;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: #EE3232;\n"
"}")
        self.close.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("../../../Downloads/close.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.close.setIcon(icon11)
        self.close.setIconSize(QtCore.QSize(18, 18))
        self.close.setObjectName("close")
        EduLab.setCentralWidget(self.centralwidget)

        self.retranslateUi(EduLab)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(EduLab)

    def retranslateUi(self, EduLab):
        _translate = QtCore.QCoreApplication.translate
        EduLab.setWindowTitle(_translate("EduLab", "EduLab"))
        self.open1_textreworker_pg3.setText(_translate("EduLab", "Исправитель текста"))
        self.ai_chat_text.setText(_translate("EduLab", "AI Чат"))
        self.label.setText(_translate("EduLab", "LLama 3-1 Api Key"))
        self.label_2.setText(_translate("EduLab", "ChatGPT Api Key"))
        self.more_settings.setText(_translate("EduLab", "Другие настройки"))
        self.background_change_text.setText(_translate("EduLab", "Изменить фон окна"))
        self.theme_text.setText(_translate("EduLab", "Тема приложения"))
        self.background_set_file_open.setText(_translate("EduLab", "Выбрать изображение"))
        self.set_black_theme.setText(_translate("EduLab", "Темная"))
        self.set_white_theme.setText(_translate("EduLab", "Белая"))
        self.checktext.setText(_translate("EduLab", "Исправить текст"))
        self.open2_translator.setText(_translate("EduLab", "Переводчик"))
        self.open3_pptxgen.setText(_translate("EduLab", "PPTX Генератор"))
        self.open4_imggen.setText(_translate("EduLab", "IMG Генератор"))
